### ISSUE TITLE
button should be center align

### ISSUE THREAD

**Issue by muhammad-ishfaq-com** [computangit/HUNT-CLUB#37]
https://prnt.sc/sb7u19

https://preview.hs-sites.com/_hcms/preview/template/multi?blog_listing=true&content_group_id=null&domain=undefined&portalId=609582&tc_deviceCategory=undefined&template_file_path=News/Home2020.html&updated=1588073780616

**Comment by computan** [comment]
Done

**Comment by muhammad-ishfaq-com** [comment]
Closed
