### ISSUE TITLE
wrong space.looks incorrect

### ISSUE THREAD

**Issue by muhammad-ishfaq-com** [computangit/HUNT-CLUB#39]
https://prnt.sc/sb8090 + https://prnt.sc/sb80pf

https://preview.hs-sites.com/_hcms/preview/template/multi?blog_listing=false&content_group_id=null&domain=undefined&portalId=609582&tc_deviceCategory=undefined&template_file_path=Blog/Post/Post2020.html&updated=1588145285798

**Comment by computan** [comment]
One issue has been fixed and the second same as the live site

**Comment by muhammad-ishfaq-com** [comment]
Closed
